const fs = require('fs');

const surahNames = [
  { no: 1, name: "Al-Fatihah", eng: "The Opening", ar: "الفاتحة" },
  { no: 2, name: "Al-Baqarah", eng: "The Cow", ar: "البقرة" },
  { no: 3, name: "Ali 'Imran", eng: "Family of Imran", ar: "آل عمران" },
  { no: 4, name: "An-Nisa'", eng: "The Women", ar: "النساء" },
  { no: 5, name: "Al-Ma'idah", eng: "The Table Spread", ar: "المائدة" },
  { no: 6, name: "Al-An'am", eng: "The Cattle", ar: "الأنعام" },
  { no: 7, name: "Al-A'raf", eng: "The Heights", ar: "الأعراف" },
  { no: 8, name: "Al-Anfal", eng: "The Spoils of War", ar: "الأنفال" },
  { no: 9, name: "At-Tawbah", eng: "The Repentance", ar: "التوبة" },
  { no: 10, name: "Yunus", eng: "Jonah", ar: "يونس" },
  { no: 11, name: "Hud", eng: "Hud", ar: "هود" },
  { no: 12, name: "Yusuf", eng: "Joseph", ar: "يوسف" },
  { no: 13, name: "Ar-Ra'd", eng: "The Thunder", ar: "الرعد" },
  { no: 14, name: "Ibrahim", eng: "Abraham", ar: "إبراهيم" },
  { no: 15, name: "Al-Hijr", eng: "The Rocky Tract", ar: "الحجر" },
  { no: 16, name: "An-Nahl", eng: "The Bee", ar: "النحل" },
  { no: 17, name: "Al-Isra'", eng: "The Night Journey", ar: "الإسراء" },
  { no: 18, name: "Al-Kahf", eng: "The Cave", ar: "الكهف" },
  { no: 19, name: "Maryam", eng: "Mary", ar: "مريم" },
  { no: 20, name: "Ta-Ha", eng: "Ta-Ha", ar: "طه" },
  { no: 21, name: "Al-Anbiya'", eng: "The Prophets", ar: "الأنبياء" },
  { no: 22, name: "Al-Hajj", eng: "The Pilgrimage", ar: "الحج" },
  { no: 23, name: "Al-Mu'minun", eng: "The Believers", ar: "المؤمنون" },
  { no: 24, name: "An-Nur", eng: "The Light", ar: "النور" },
  { no: 25, name: "Al-Furqan", eng: "The Criterion", ar: "الفرقان" },
  { no: 26, name: "Ash-Shu'ara'", eng: "The Poets", ar: "الشعراء" },
  { no: 27, name: "An-Naml", eng: "The Ant", ar: "النمل" },
  { no: 28, name: "Al-Qasas", eng: "The Stories", ar: "القصص" },
  { no: 29, name: "Al-'Ankabut", eng: "The Spider", ar: "العنكبوت" },
  { no: 30, name: "Ar-Rum", eng: "The Romans", ar: "الروم" },
  { no: 31, name: "Luqman", eng: "Luqman", ar: "لقمان" },
  { no: 32, name: "As-Sajdah", eng: "The Prostration", ar: "السجدة" },
  { no: 33, name: "Al-Ahzab", eng: "The Combined Forces", ar: "الأحزاب" },
  { no: 34, name: "Saba'", eng: "Sheba", ar: "سبأ" },
  { no: 35, name: "Fatir", eng: "The Originator", ar: "فاطر" },
  { no: 36, name: "Ya-Sin", eng: "Ya-Sin", ar: "يس" },
  { no: 37, name: "As-Saffat", eng: "Those who set the Ranks", ar: "الصافات" },
  { no: 38, name: "Sad", eng: "The Letter Sad", ar: "ص" },
  { no: 39, name: "Az-Zumar", eng: "The Troops", ar: "الزمر" },
  { no: 40, name: "Ghafir", eng: "The Forgiver", ar: "غافر" },
  { no: 41, name: "Fussilat", eng: "Explained in Detail", ar: "فصلت" },
  { no: 42, name: "Ash-Shura", eng: "The Consultation", ar: "الشورى" },
  { no: 43, name: "Az-Zukhruf", eng: "The Ornaments of Gold", ar: "الزخرف" },
  { no: 44, name: "Ad-Dukhan", eng: "The Smoke", ar: "الدخان" },
  { no: 45, name: "Al-Jathiyah", eng: "The Crouching", ar: "الجاثية" },
  { no: 46, name: "Al-Ahqaf", eng: "The Wind-Curved Sandhills", ar: "الأحقاف" },
  { no: 47, name: "Muhammad", eng: "Muhammad", ar: "محمد" },
  { no: 48, name: "Al-Fath", eng: "The Victory", ar: "الفتح" },
  { no: 49, name: "Al-Hujurat", eng: "The Dwellings", ar: "الحجرات" },
  { no: 50, name: "Qaf", eng: "The Letter Qaf", ar: "ق" },
  { no: 51, name: "Adh-Dhariyat", eng: "The Winnowing Winds", ar: "الذاريات" },
  { no: 52, name: "At-Tur", eng: "The Mount", ar: "الطور" },
  { no: 53, name: "An-Najm", eng: "The Star", ar: "النجم" },
  { no: 54, name: "Al-Qamar", eng: "The Moon", ar: "القمر" },
  { no: 55, name: "Ar-Rahman", eng: "The Beneficent", ar: "الرحمن" },
  { no: 56, name: "Al-Waqi'ah", eng: "The Inevitable", ar: "الواقعة" },
  { no: 57, name: "Al-Hadid", eng: "The Iron", ar: "الحديد" },
  { no: 58, name: "Al-Mujadilah", eng: "The Pleading Woman", ar: "المجادلة" },
  { no: 59, name: "Al-Hashr", eng: "The Exile", ar: "الحشر" },
  { no: 60, name: "Al-Mumtahanah", eng: "She that is to be examined", ar: "الممتحنة" },
  { no: 61, name: "As-Saff", eng: "The Ranks", ar: "الصف" },
  { no: 62, name: "Al-Jumu'ah", eng: "The Congregation, Friday", ar: "الجمعة" },
  { no: 63, name: "Al-Munafiqun", eng: "The Hypocrites", ar: "المنافقون" },
  { no: 64, name: "At-Taghabun", eng: "The Mutual Disillusion", ar: "التغابن" },
  { no: 65, name: "At-Talaq", eng: "The Divorce", ar: "الطلاق" },
  { no: 66, name: "At-Tahrim", eng: "The Prohibition", ar: "التحريم" },
  { no: 67, name: "Al-Mulk", eng: "The Sovereignty", ar: "الملك" },
  { no: 68, name: "Al-Qalam", eng: "The Pen", ar: "القلم" },
  { no: 69, name: "Al-Haqqah", eng: "The Reality", ar: "الحاقة" },
  { no: 70, name: "Al-Ma'arij", eng: "The Ascending Stairways", ar: "المعارج" },
  { no: 71, name: "Nuh", eng: "Noah", ar: "نوح" },
  { no: 72, name: "Al-Jinn", eng: "The Jinn", ar: "الجن" },
  { no: 73, name: "Al-Muzzammil", eng: "The Enshrouded One", ar: "المزمل" },
  { no: 74, name: "Al-Muddaththir", eng: "The Cloaked One", ar: "المدثر" },
  { no: 75, name: "Al-Qiyamah", eng: "The Resurrection", ar: "القيامة" },
  { no: 76, name: "Al-Insan", eng: "Man", ar: "الإنسان" },
  { no: 77, name: "Al-Mursalat", eng: "The Emissaries", ar: "المرسلات" },
  { no: 78, name: "An-Naba'", eng: "The Tidings", ar: "النبأ" },
  { no: 79, name: "An-Nazi'at", eng: "Those who drag forth", ar: "النازعات" },
  { no: 80, name: "'Abasa", eng: "He frowned", ar: "عبس" },
  { no: 81, name: "At-Takwir", eng: "The Overthrowing", ar: "التكوير" },
  { no: 82, name: "Al-Infitar", eng: "The Cleaving", ar: "الانفطار" },
  { no: 83, name: "Al-Mutaffifin", eng: "Defrauding", ar: "المطففين" },
  { no: 84, name: "Al-Inshiqaq", eng: "The Sundering", ar: "الانشقاق" },
  { no: 85, name: "Al-Buruj", eng: "The Mansions of the Stars", ar: "البروج" },
  { no: 86, name: "At-Tariq", eng: "The Morning Star", ar: "الطارق" },
  { no: 87, name: "Al-A'la", eng: "The Most High", ar: "الأعلى" },
  { no: 88, name: "Al-Ghashiyah", eng: "The Overwhelming", ar: "الغاشية" },
  { no: 89, name: "Al-Fajr", eng: "The Dawn", ar: "الفجر" },
  { no: 90, name: "Al-Balad", eng: "The City", ar: "البلد" },
  { no: 91, name: "Ash-Shams", eng: "The Sun", ar: "الشمس" },
  { no: 92, name: "Al-Layl", eng: "The Night", ar: "الليل" },
  { no: 93, name: "Ad-Duha", eng: "The Morning Hours", ar: "الضحى" },
  { no: 94, name: "Ash-Sharh", eng: "The Relief", ar: "الشرح" },
  { no: 95, name: "At-Tin", eng: "The Fig", ar: "التين" },
  { no: 96, name: "Al-'Alaq", eng: "The Clot", ar: "العلق" },
  { no: 97, name: "Al-Qadr", eng: "The Power", ar: "القدر" },
  { no: 98, name: "Al-Bayyinah", eng: "The Clear Proof", ar: "البينة" },
  { no: 99, name: "Az-Zalzalah", eng: "The Earthquake", ar: "الزلزلة" },
  { no: 100, name: "Al-'Adiyat", eng: "The Courser", ar: "العاديات" },
  { no: 101, name: "Al-Qari'ah", eng: "The Calamity", ar: "القارعة" },
  { no: 102, name: "At-Takathur", eng: "The Rivalry in World Increase", ar: "التكاثر" },
  { no: 103, name: "Al-'Asr", eng: "The Declining Day", ar: "العصر" },
  { no: 104, name: "Al-Humazah", eng: "The Traducer", ar: "الهمزة" },
  { no: 105, name: "Al-Fil", eng: "The Elephant", ar: "الفيل" },
  { no: 106, name: "Quraysh", eng: "Quraysh", ar: "قريش" },
  { no: 107, name: "Al-Ma'un", eng: "Small Kindnesses", ar: "الماعون" },
  { no: 108, name: "Al-Kawthar", eng: "Abundance", ar: "الكوثر" },
  { no: 109, name: "Al-Kafirun", eng: "The Disbelievers", ar: "الكافرون" },
  { no: 110, name: "An-Nasr", eng: "The Divine Support", ar: "النصر" },
  { no: 111, name: "Al-Masad", eng: "The Palm Fiber", ar: "المسد" },
  { no: 112, name: "Al-Ikhlas", eng: "The Sincerity", ar: "الإخلاص" },
  { no: 113, name: "Al-Falaq", eng: "The Daybreak", ar: "الفلق" },
  { no: 114, name: "An-Nas", eng: "Mankind", ar: "الناس" }
];

try {
  const quran = JSON.parse(fs.readFileSync('public/quran.json', 'utf8'));
  
  // Count verses for each surah
  const counts = {};
  quran.forEach(v => {
    counts[v.s] = (counts[v.s] || 0) + 1;
  });

  const fullSurahs = surahNames.map(s => ({
    ...s,
    verses: counts[s.no] || 0
  }));

  fs.writeFileSync('public/surahs.json', JSON.stringify(fullSurahs, null, 2));
  console.log(`Saved surahs.json with ${fullSurahs.length} surahs.`);
} catch (e) {
  console.error('Error:', e);
}
